# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  venv:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up virtual environment
        run: |
            python3 -m venv .venv
            source .venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest
            pip install ruff
            pip install black

  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Test with pytest
        run: |
          source .venv/bin/activate
          pytest

  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Lint with ruff
        run: |
          source .venv/bin/activate
          ruff check

  format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Format with black
        run: |
          source .venv/bin/activate
          black --check